package medicaments.classes;

import java.util.ArrayList;


/**
 * Avis class, this is used to modelized a avis stored in the DB
 * @author Basile, Loic
 *
 */
public class Avis {

	/** ID of the avis **/
	private int id;
	/** CIS code, identifier of the medicament **/
	private int codeCIS;
	/** **/
	private String codeDossierHAS;
	/** Why the medicament has been evaluated **/
	private String motifEval;
	/** Date of the evaluation **/
	private String date;
	/** Value of the evaluation **/
	private String valeur;
	/** Name of the evaluation **/
	private String libelle;
	/** Type of evaluation : either SMR or ASMR **/
	private String typeEvaluation;
	
	private ArrayList<String> avis_CT;

	/**
	 * Create an avis
	 * 
	 * The field must be completed with the setters
	 */
	public Avis() {}
	
	/**
	 * Create an avis with attributes
	 */
	public Avis(int codeCIS, String codeDossierHAS, String motifEval, String date, 
			String valeur, String libelle) {
		avis_CT = new ArrayList<String>();
		this.codeCIS = codeCIS;
		this.codeDossierHAS = codeDossierHAS;
		this.motifEval = motifEval;
		this.date = date;
		this.valeur = valeur;
		this.libelle = libelle;
	}

	/** BEGINING OF AUTOGENERATED GETTERS /SETTERS **/

	public void addLienCT(String lien) {
		this.avis_CT.add(lien);
	}
	
	
	public ArrayList<String> getListLienCT() {
		return this.avis_CT;
	}
	
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCodeCIS() {
		return codeCIS;
	}

	public void setCodeCIS(int codeCIS) {
		this.codeCIS = codeCIS;
	}

	public String getCodeDossierHAS() {
		return codeDossierHAS;
	}

	public void setCodeDossierHAS(String codeDossierHAS) {
		this.codeDossierHAS = codeDossierHAS;
	}

	public String getMotifEval() {
		return motifEval;
	}

	public void setMotifEval(String motifEval) {
		this.motifEval = motifEval;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getValeur() {
		return valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	public String getLibelle() {
		return libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getTypeEvaluation() {
		return typeEvaluation;
	}

	public void setTypeEvaluation(String typeEvaluation) {
		this.typeEvaluation = typeEvaluation;
	}
	
	/** END OF AUTOGENERATED GETTERS /SETTERS **/

	@Override
	public String toString() {
		return "Avis [id=" + id + ", codeCIS=" + codeCIS + ", codeDossierHAS=" + codeDossierHAS + ", motifEval="
				+ motifEval + ", date=" + date + ", valeur=" + valeur + ", libelle=" + libelle + ", typeEvaluation="
				+ typeEvaluation + "]";
	}
	
}
